// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVqfate1nVAeACRx3BcSpIYjmjSXGJsAk',
    appId: '1:687975541007:web:c2b8a06d86a82fae54f67a',
    messagingSenderId: '687975541007',
    projectId: 'wajed-5d677',
    authDomain: 'wajed-5d677.firebaseapp.com',
    storageBucket: 'wajed-5d677.firebasestorage.app',
    measurementId: 'G-LTJVWM03B9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn1RL_SXrjJxgcsI3t07FH37MREkg4NAM',
    appId: '1:687975541007:android:63e88956d879079c54f67a',
    messagingSenderId: '687975541007',
    projectId: 'wajed-5d677',
    storageBucket: 'wajed-5d677.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQXuvapSGtEuFsbr8T0xsXR4QYB33_GSI',
    appId: '1:687975541007:ios:23d93a9f5c0d72d454f67a',
    messagingSenderId: '687975541007',
    projectId: 'wajed-5d677',
    storageBucket: 'wajed-5d677.firebasestorage.app',
    iosBundleId: 'com.example.wajeed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQXuvapSGtEuFsbr8T0xsXR4QYB33_GSI',
    appId: '1:687975541007:ios:23d93a9f5c0d72d454f67a',
    messagingSenderId: '687975541007',
    projectId: 'wajed-5d677',
    storageBucket: 'wajed-5d677.firebasestorage.app',
    iosBundleId: 'com.example.wajeed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVqfate1nVAeACRx3BcSpIYjmjSXGJsAk',
    appId: '1:687975541007:web:6fa6a141cb0b4ef054f67a',
    messagingSenderId: '687975541007',
    projectId: 'wajed-5d677',
    authDomain: 'wajed-5d677.firebaseapp.com',
    storageBucket: 'wajed-5d677.firebasestorage.app',
    measurementId: 'G-GQ6VY5320V',
  );
}
